app:
  host: 'localhost'
  port: '9123'
  open: 'true'
daemon:
  port: '9124'
editor:
  theme:       'cobalt'     # see https://github.com/ajaxorg/ace/tree/master/lib/ace/theme
  indentation: '2 spaces'   # spaces or tabs
  font-size:   '13px'
  extensions:               # for syntax highlighting: given a file extension, of which language shall we consider that file?
    json:       'json'
    markdown:   'markdown'
    md:         'markdown'
    yml:        'yaml'
    js:         'javascript'
    coffee:     'coffescript'
    html:       'html'
    rb:         'ruby'
    php:        'php'
    sql:        'sql'
    py:         'python'
    java:       'java'
    css:        'css'
    scss:       'scss'
    c:          'c'
    xml:        'xml'    
projects:
  default: 'cwd'            # the project we should open by default: can be an absolute path (/var/www), a relative one (~/projects) or the directory from which you launch nikki (cwd)
  ignore:                   # files or directories to ignore
    - '.git'
    - '.svn'
    - '.idea'
search:
  timeout:  '300'           # nikki will let you type for these many milliseconds before triggering a search with your input (decreasing this impacts performances and accuracy)
  exclude:                  # files or directories to exclude
    - '.git'
    - '.svn'
    - '.idea'
    - 'bower_components'
    - 'node_modules'
github:                         # these configs will affect the "Open in Github" shortcut (ctrl + g)
  enabled: false                # disabled by default, you need to configure the following lines wisely :)
  username: 'your GH username'  # your github username
  path: '/home/USER/projects'   # absolute path to your github projects (ie. myProject is in /home/USER/projects/myProject)
  default_branch: 'master'
general:
  process-name: 'nikki'         # name of the process you will find under ps -ef